include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  language:
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:

    # -------------------------
    # Legibilidad 
    # -------------------------
    - avoid_bool_literals_in_conditional_expressions
    - prefer_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_this
    - require_trailing_commas

    # -------------------------
    # Evitar código innecesario
    # -------------------------
    - avoid_redundant_argument_values
    - unnecessary_statements
    - avoid_returning_null_for_void

    # -------------------------
    # Buenas prácticas 
    # -------------------------
    - always_declare_return_types
    - avoid_dynamic_calls
    - prefer_final_fields
    - prefer_final_locals

    # -------------------------
    # Performance 
    # -------------------------
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables

    # -------------------------
    # Código sucio
    # -------------------------
    - avoid_print

    # -------------------------
    # Flutter UI
    # -------------------------
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers

dart_code_metrics:

  metrics:
    cyclomatic-complexity: 10
    maximum-nesting-level: 3
    number-of-parameters: 4
    source-lines-of-code: 50

  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  rules:
    - avoid-nested-conditional-expressions
    - avoid-non-null-assertion
    - avoid-unnecessary-type-casts
    - prefer-trailing-comma
