# sonar.projectKey=secure_vault_app

#Config SonarCloud
sonar.projectKey=alejandra11r_secure_vault_app
sonar.organization=Alejandra11r
#sonar.dart.lcov.reportPaths=coverage/lcov.info

#sonar.projectName=Secure Vault App
#sonar.projectVersion=1.0


sonar.sources=lib

#sonar.sourceEncoding=UTF-8

# Excluir archivos generados
#sonar.exclusions=**/*.g.dart,**/*.freezed.dart,build/**

#sonar.language=dart
#sonar.inclusions=**/*.dart