// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT5ABWudNWDq1xMCm2c8heAG5QglIaloE',
    appId: '1:583005459695:web:ff6fe8b4eaf5b7d1ef371a',
    messagingSenderId: '583005459695',
    projectId: 'vaultapp-cc07b',
    authDomain: 'vaultapp-cc07b.firebaseapp.com',
    storageBucket: 'vaultapp-cc07b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMcYknllIjvIE-w9DSPBAQkffNrH1e9U',
    appId: '1:583005459695:android:8ef1fe22e1c1118def371a',
    messagingSenderId: '583005459695',
    projectId: 'vaultapp-cc07b',
    storageBucket: 'vaultapp-cc07b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6vIMSiNzSmNHI5RiMeRg3ccmgIk3yr4',
    appId: '1:583005459695:ios:2b260cf435f18338ef371a',
    messagingSenderId: '583005459695',
    projectId: 'vaultapp-cc07b',
    storageBucket: 'vaultapp-cc07b.firebasestorage.app',
    iosBundleId: 'com.example.secureVaultApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6vIMSiNzSmNHI5RiMeRg3ccmgIk3yr4',
    appId: '1:583005459695:ios:2b260cf435f18338ef371a',
    messagingSenderId: '583005459695',
    projectId: 'vaultapp-cc07b',
    storageBucket: 'vaultapp-cc07b.firebasestorage.app',
    iosBundleId: 'com.example.secureVaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT5ABWudNWDq1xMCm2c8heAG5QglIaloE',
    appId: '1:583005459695:web:1a234f3909e44699ef371a',
    messagingSenderId: '583005459695',
    projectId: 'vaultapp-cc07b',
    authDomain: 'vaultapp-cc07b.firebaseapp.com',
    storageBucket: 'vaultapp-cc07b.firebasestorage.app',
  );
}
